### ISSUE TITLE
Create UI Mockup for Settings Page

### ISSUE THREAD

**Issue by rykieldc** [rykieldc/cc17-3k-uti#12]
**About the Settings Page:**
- Users should have access to a settings page, which should include controls for:
    - **Notification Settings**: Manage alerts for low stock, restocking, and activity notifications.
    - **Display and Personalization**: Options for theme (light/dark mode)
    - **About**: Information about the application version, terms and conditions, privacy policy, and support contact details.

**Task:** 
- [ ] Create a page for managing notification settings, display options, and viewing application details (version, terms, and support).

**Comment by shanebergado** [comment]
Started working for this page.

**Comment by shanebergado** [comment]
Status: Ongoing
Completed: Partially Completed
Next Step: Polishing of Designs
Blockers: Aligning

**Comment by rykieldc** [comment]
Tasks Done for Today:

- Added account tab
  - Contains:
      - Change Password Option
      - Logout Option

- Added about tab
