### ISSUE TITLE
Create UI Mockup for Manage Users Page

### ISSUE THREAD

**Issue by rykieldc** [rykieldc/cc17-3k-uti#13]
**About the Manage Users Page:**
- Super admins should have the ability to manage users to the application.
- Access to this page should be restricted exclusively to super admins, and it should include options to set user roles and permissions.

**Task:** 
- [ ] Create an interface for super admins to add, edit, or remove users, set roles, and manage user permissions.

**Comment by shanebergado** [comment]
Started making it.

**Comment by rykieldc** [comment]
Tasks Done Today:

- Added page to view all users with search and filtering
- Added Add, Edit, and Delete User Button
- Created Add User Form
- Created Edit User Form
- Added confirmation dialog for saving/cancelling changes and deleting users
