### ISSUE TITLE
Create UI Mockup for Dashboard Page

### ISSUE THREAD

**Issue by rykieldc** [rykieldc/cc17-3k-uti#3]
**About the Dashboard Page:**
- The dashboard should provide users with options to add, edit, delete, or view items through clearly labeled buttons.
- Users should see an "Alert" button to access notifications for low stock or restocking needs.
- Users should have a "Profile" button to access their personal information and account settings.
- A "Settings" button should be available for accessing application settings.
- Super admins should have exclusive access to an "Add New User" button to create new users.
- Super admins should also have access to a "History" page to view logs of all user activities.

**Task:** 
- [ ] Create a central hub displaying buttons for adding, editing, deleting, and viewing items. Include access to alerts, profile, settings, and admin features (add new user, history).

**Comment by AcederaCy** [comment]
Tasks Done Today:

Client-Side:
- Added buttons for adding, editing, deleting, and viewing items
- Added navigation bar for profile, alerts/notifications, settings

Admin-Side:
- Added buttons for adding, editing, deleting, and viewing items
- Added navigation bar for profile, alerts/notifications, settings
- Added buttons for user management page and history page to view logs
