### ISSUE TITLE
Create UI Mockup for Profile Page

### ISSUE THREAD

**Issue by rykieldc** [rykieldc/cc17-3k-uti#5]
**About the Profile Page:**
- Users should be able to view their profile information, such as name, email, and role.
- Users should be able to change their password.
- The page should provide a logout option to securely exit the application.

**Task:** 
- [ ] Design a profile page where users can view personal information, change passwords, and log out.

**Comment by shanebergado** [comment]
I started working for the profile page in the morning.

**Comment by shanebergado** [comment]
Status: Ongoing
Completed: The logo and bars
Next Stop: Icons
Blockers: It's hard to finalize and think what is the appropriate visuals for our UI.
