### ISSUE TITLE
Create UI Mockup for Alerts Page

### ISSUE THREAD

**Issue by rykieldc** [rykieldc/cc17-3k-uti#9]
**About the Alerts Page:**
- Users should receive alerts for items that require restocking or have reached low stock levels.
- Alerts should be customizable based on inventory thresholds defined by the user or admin.

**Task:** 
- [ ] Design an interface displaying notifications for low stock or restocking needs, with customizable alert thresholds.

**Comment by shanebergado** [comment]
Started making it.

**Comment by rykieldc** [comment]
Tasks Done Today:

- Added sample alerts on the notifications page
